{
  "openapi": "3.0.0",
  "info": {
    "title": "booking_management",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "localhost://"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "get_authorization_token"
    },
    {
      "name": "users"
    },
    {
      "name": "auth"
    },
    {
      "name": "role"
    },
    {
      "name": "hotel"
    },
    {
      "name": "hotel > room"
    },
    {
      "name": "spaces"
    },
    {
      "name": "automobiles"
    },
    {
      "name": "typeidentifier"
    },
    {
      "name": "addcategoryamenities"
    },
    {
      "name": "orders"
    },
    {
      "name": "transaction"
    },
    {
      "name": "payment"
    }
  ],
  "paths": {
    "/000/api/getauthorizationtoken": {
      "get": {
        "tags": ["get_authorization_token"],
        "summary": "get_authorization_token",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/adduser": {
      "post": {
        "tags": ["users"],
        "summary": "adduser",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "first_name": "Muskan",
                  "last_name": "Ved",
                  "email": "muskanved@gmail.com",
                  "phone_number": "9131649079",
                  "password": "Shubham#12",
                  "role_id": 2
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getusers": {
      "get": {
        "tags": ["users"],
        "summary": "getusers",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getuser/2": {
      "get": {
        "tags": ["users"],
        "summary": "getuser",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/deleteuser/3": {
      "delete": {
        "tags": ["users"],
        "summary": "deleteuser",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/edituser/3": {
      "put": {
        "tags": ["users"],
        "summary": "edituser",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "first_name": "Muskan ved",
                  "last_name": "ved",
                  "email": "mvved@gmail.com",
                  "phone_number": "7089413024",
                  "date_of_birth": "1999-11-02"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/edituserprofilepicture/3": {
      "put": {
        "tags": ["users"],
        "summary": "editprofilepicture",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "image": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/userlogin": {
      "post": {
        "tags": ["auth"],
        "summary": "userlogin",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "mvved@gmail.com",
                  "password": "Shubham#12"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/forgotpassword": {
      "post": {
        "tags": ["auth"],
        "summary": "forgotpassword",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "mvved@gmail.com"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/resetpassword": {
      "post": {
        "tags": ["auth"],
        "summary": "resertpassword",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im12dmVkQGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE2OTE3MzQ0OTIsImV4cCI6MTY5MTc2MzI5Mn0.5KRh_aGs8hUXljqauAfx6HhmkUnipIQcFzVNy79PKAU",
                  "password": "Shubham#12"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addrole": {
      "post": {
        "tags": ["role"],
        "summary": "addrole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "customer"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getroles": {
      "get": {
        "tags": ["role"],
        "summary": "getroles",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/editrole/1": {
      "put": {
        "tags": ["role"],
        "summary": "editrole",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "customer"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addroom": {
      "post": {
        "tags": ["hotel > room"],
        "summary": "addroom",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "Premium Room12234"
                  },
                  "room_number": {
                    "type": "integer",
                    "example": "201"
                  },
                  "description": {
                    "type": "number",
                    "example": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32."
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "gallary_image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "guest_capacity": {
                    "type": "integer",
                    "example": "2"
                  },
                  "room_type": {
                    "type": "string",
                    "example": "single"
                  },
                  "status": {
                    "type": "integer",
                    "example": "1"
                  },
                  "cost_per_day": {
                    "type": "integer",
                    "example": "200"
                  },
                  "cost_per_hour": {
                    "type": "integer",
                    "example": "200"
                  },
                  "room_size": {
                    "type": "string",
                    "example": "301 sq.ft"
                  },
                  "hotel_id": {
                    "type": "integer",
                    "example": "1"
                  },
                  "": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTY0NDYzNiwiZXhwIjoxNjkxNjczNDM2fQ.f0LGi7z81ljvl5xDXQsP2CjsM4h0G1xDXcVxkLV3fNA"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getrooms": {
      "get": {
        "tags": ["hotel > room"],
        "summary": "getrooms",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getroom/1": {
      "get": {
        "tags": ["hotel > room"],
        "summary": "getroom",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getroomesbyhotelid/1": {
      "get": {
        "tags": ["hotel > room"],
        "summary": "getroomsbyhotelid",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/": {
      "put": {
        "tags": ["hotel > room"],
        "summary": "editroom",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "room1"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTEyNTQ0NywiZXhwIjoxNjkxMTU0MjQ3fQ.deYGEFGe5L7f0DpOnfxsxm5loHJpzWzHe_4Zof_znug"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addhotel": {
      "post": {
        "tags": ["hotel"],
        "summary": "addhotel",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "Hotel  Grande Vijay Nagar Indore243"
                  },
                  "slug": {
                    "type": "string",
                    "example": "Hotel_Meritel_Grande_Vijay_Nagar_Indore"
                  },
                  "short_description": {
                    "type": "number",
                    "example": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32."
                  },
                  "long_description": {
                    "type": "number",
                    "example": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32."
                  },
                  "availability": {
                    "type": "string",
                    "example": "[{\"day\":\"monday\",\"status\":\"true\",\"start_time\":\"9:00:AM\",\"close_time\":\"11:00:PM\",\"date\":\"2000-02-12\"},{\"day\":\"tuesday\",\"status\":\"true\",\"start_time\":\"9:00:AM\",\"close_time\":\"11:00:PM\",\"date\":\"2000-02-12\"}]"
                  },
                  "status": {
                    "type": "integer",
                    "example": "1"
                  },
                  "user_id": {
                    "type": "integer",
                    "example": "2"
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "gallary_image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "location": {
                    "type": "number",
                    "example": "{\"latitude\":\"22.719568\",\"longitude\":\"75.857727\""
                  },
                  "city": {
                    "type": "string",
                    "example": "indore"
                  },
                  "booking_type": {
                    "type": "string",
                    "example": "{\"is_hourly_booking\":true, \"is_day_boking\":true,\"is_monthly_booking\":true}"
                  },
                  "cancellation_pilicy": {
                    "type": "string",
                    "example": "[\"Ani\", \"Sam\", \"Joe\"]"
                  },
                  "terms_condition": {
                    "type": "string",
                    "example": "[\"Ani\", \"Sam\", \"Joe\"]"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTY0NDYzNiwiZXhwIjoxNjkxNjczNDM2fQ.f0LGi7z81ljvl5xDXQsP2CjsM4h0G1xDXcVxkLV3fNA"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gethotels": {
      "get": {
        "tags": ["hotel"],
        "summary": "gethotels",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gethotel/1": {
      "get": {
        "tags": ["hotel"],
        "summary": "gethotel",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/edithotel/1": {
      "put": {
        "tags": ["hotel"],
        "summary": "edithotel",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "dsjfkhgk"
                  },
                  "slug": {
                    "type": "string",
                    "example": "dsfelisdof"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTA3MTE3NCwiZXhwIjoxNjkxMDk5OTc0fQ.qDDwh9Wl5WqJ6EN7g3McBqJtvCqj6yqILSUedysI_-Q"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/deletehotel/2": {
      "delete": {
        "tags": ["hotel"],
        "summary": "deletehotel",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTA3MTE3NCwiZXhwIjoxNjkxMDk5OTc0fQ.qDDwh9Wl5WqJ6EN7g3McBqJtvCqj6yqILSUedysI_-Q"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gethotelcategories": {
      "get": {
        "tags": ["hotel"],
        "summary": "gethotelcategories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "type_identifier_id",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "1"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gethotelamenities": {
      "get": {
        "tags": ["hotel"],
        "summary": "gethotelamenities",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addspace": {
      "post": {
        "tags": ["spaces"],
        "summary": "addspace",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "Banquete Hall123"
                  },
                  "slug": {
                    "type": "string",
                    "example": "Banquete_Hall"
                  },
                  "status": {
                    "type": "integer",
                    "example": "1"
                  },
                  "space_size": {
                    "type": "string",
                    "example": "121 sq ft"
                  },
                  "guest_capacity": {
                    "type": "integer",
                    "example": "20"
                  },
                  "space_type": {
                    "type": "string",
                    "example": "Premium"
                  },
                  "cost_per_hour": {
                    "type": "integer",
                    "example": "100"
                  },
                  "cost_per_day": {
                    "type": "integer",
                    "example": "200"
                  },
                  "short_description": {
                    "type": "number",
                    "example": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32."
                  },
                  "long_description": {
                    "type": "number",
                    "example": "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32."
                  },
                  "avalability": {
                    "type": "string",
                    "example": "[{\"day\":\"monday\",\"status\":\"true\",\"start_time\":\"9:00:AM\",\"close_time\":\"11:00:PM\",\"date\":\"2000-02-12\"},{\"day\":\"tuesday\",\"status\":\"true\",\"start_time\":\"9:00:AM\",\"close_time\":\"11:00:PM\",\"date\":\"2000-02-12\"}]"
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "gallary_image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "location": {
                    "type": "number",
                    "example": "{\"latitude\":\"22.719568\",\"longitude\":\"75.857727\""
                  },
                  "city": {
                    "type": "string",
                    "example": "Indore"
                  },
                  "booking_type": {
                    "type": "string",
                    "example": "{\"is_hourly_booking\":true, \"is_day_boking\":true,\"is_monthly_booking\":true}"
                  },
                  "cancellation_pilicy": {
                    "type": "string",
                    "example": "[\"Ani\", \"Sam\", \"Joe\"]"
                  },
                  "terms_condition": {
                    "type": "string",
                    "example": "[\"Ani\", \"Sam\", \"Joe\"]"
                  },
                  "user_id": {
                    "type": "integer",
                    "example": "2"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTY0NDYzNiwiZXhwIjoxNjkxNjczNDM2fQ.f0LGi7z81ljvl5xDXQsP2CjsM4h0G1xDXcVxkLV3fNA"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getspaces": {
      "get": {
        "tags": ["spaces"],
        "summary": "getspaces",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getspace/3": {
      "get": {
        "tags": ["spaces"],
        "summary": "getspace",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/editspace/3": {
      "put": {
        "tags": ["spaces"],
        "summary": "editspace",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "hii"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTE0NDUwMywiZXhwIjoxNjkxMTczMzAzfQ.or4RTXgxA1lE7x7oXfG0Vruk2UDXVEn2ij1Y46Q58aw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/deletespace/3": {
      "delete": {
        "tags": ["spaces"],
        "summary": "deletespace",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTE0NDUwMywiZXhwIjoxNjkxMTczMzAzfQ.or4RTXgxA1lE7x7oXfG0Vruk2UDXVEn2ij1Y46Q58aw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getspacescategories": {
      "get": {
        "tags": ["spaces"],
        "summary": "getspacecategories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "type_identifier_id",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "3"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getspacesamenities": {
      "get": {
        "tags": ["spaces"],
        "summary": "getspaceamenities",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addautomobile": {
      "post": {
        "tags": ["automobiles"],
        "summary": "addautomobile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "auto_mobile_categories": {
                    "type": "string",
                    "example": "bike"
                  },
                  "auto_mobile_name": {
                    "type": "string",
                    "example": "CD Delux 125"
                  },
                  "auto_mobile_number": {
                    "type": "string",
                    "example": "MP-17-IN-124"
                  },
                  "auto_mobile_brand": {
                    "type": "string",
                    "example": "Hero Honda"
                  },
                  "auto_mobile_type": {
                    "type": "string",
                    "example": "sedan"
                  },
                  "user_id": {
                    "type": "integer",
                    "example": "1"
                  },
                  "rc_number": {
                    "type": "string",
                    "example": "835947dhjsfksg"
                  },
                  "seater": {
                    "type": "integer",
                    "example": "2"
                  },
                  "cost_per_km": {
                    "type": "integer",
                    "example": "200"
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "gallary_image": {
                    "type": "string",
                    "format": "binary"
                  },
                  "status": {
                    "type": "integer",
                    "example": "1"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTY2MDQ2MiwiZXhwIjoxNjkxNjg5MjYyfQ.e9hW5a_V8Bc2fET6gtE1VZY2peZABPJfhOSk-P4I6IQ"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getautomobiles": {
      "get": {
        "tags": ["automobiles"],
        "summary": "getautomobiles",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getautomobile/13": {
      "get": {
        "tags": ["automobiles"],
        "summary": "getautomobile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/editautomobile/1": {
      "put": {
        "tags": ["automobiles"],
        "summary": "editautomobile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "auto_mobile_categories": {
                    "type": "string",
                    "example": "car"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTE1MDQ5MSwiZXhwIjoxNjkxMTc5MjkxfQ.CH1nAwsGiuwNa2oWoZTTbYUb9Xap8qj5Ojxl78aSKPU"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/deleteautomobile/2": {
      "delete": {
        "tags": ["automobiles"],
        "summary": "deleteautomobile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTE1MDQ5MSwiZXhwIjoxNjkxMTc5MjkxfQ.CH1nAwsGiuwNa2oWoZTTbYUb9Xap8qj5Ojxl78aSKPU"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getautomobilecategories": {
      "get": {
        "tags": ["automobiles"],
        "summary": "getautomobilecategories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "type_identifier_id",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "5"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gettypeidentifiers": {
      "get": {
        "tags": ["typeidentifier"],
        "summary": "gettypeidentifiers",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addtypeidentifier": {
      "get": {
        "tags": ["typeidentifier"],
        "summary": "addtypeidentifier",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQwNjEzOCwiZXhwIjoxNjkxNDM0OTM4fQ.AMfd5xucTodAeqra4iUU-AVgjrwtbKcTOStx5E5BxTA"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addcategoriesoramenities": {
      "post": {
        "tags": ["addcategoryamenities"],
        "summary": "addcategoriesamenities",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Projector",
                  "slug": "Projector",
                  "type_identifier_id": 4
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQwMzAwOSwiZXhwIjoxNjkxNDMxODA5fQ.XQ5npKOEj4Qa3b1-zyQqQJKwhMiweq4IDEiDZ7JK3vQ"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getcategoriesamenities/15": {
      "get": {
        "tags": ["addcategoryamenities"],
        "summary": "getcatamtbyid",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/editcategoriesamenities/15": {
      "put": {
        "tags": ["addcategoryamenities"],
        "summary": "editcatamtbtid",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "Meeting hall"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQwNjEzOCwiZXhwIjoxNjkxNDM0OTM4fQ.AMfd5xucTodAeqra4iUU-AVgjrwtbKcTOStx5E5BxTA"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getcategoriesamenities": {
      "get": {
        "tags": ["addcategoryamenities"],
        "summary": "getcategoriesamenitiesbytypeidentifierid",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "type_identifier_id",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "example": "4"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addorder": {
      "post": {
        "tags": ["orders"],
        "summary": "addautomobileorder",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "status": 1,
                  "order_type": "autoobile_order",
                  "amount": 200,
                  "unique_transaction_id": "Trx-123456789YYYYY",
                  "user_id": "1",
                  "automobile_id": 1,
                  "driver_id": 2,
                  "transaction_id": 1,
                  "auto_mobile_source": "",
                  "auto_mobile_destination": "",
                  "check_in_datetime": "",
                  "check_out_datetime": ""
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "number"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNqMjU4NTA5N0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IlNodWJoYW0jMTIiLCJpYXQiOjE2OTE1ODU1NjAsImV4cCI6MTY5MTYyODc2MH0.6us5DvxObJhwHFI7_QtUV8gajoUWtWlHRfnDFb97vzc"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getorders": {
      "get": {
        "tags": ["orders"],
        "summary": "getorders",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getorder/2": {
      "get": {
        "tags": ["orders"],
        "summary": "getorderrdetails",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/addtransaction": {
      "post": {
        "tags": ["transaction"],
        "summary": "addtransaction",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "order_id": 2,
                  "amount": 200,
                  "txn_id": "bvgfhngfhnjgf",
                  "payment_method": "stripe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQ2OTE0MywiZXhwIjoxNjkxNDk3OTQzfQ.pc9pLzB5nPOKxmdX_Sf5V_n5xNLRbU31K9nRktki3vw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gettransactions": {
      "get": {
        "tags": ["transaction"],
        "summary": "gettransactions",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/gettransaction/1": {
      "get": {
        "tags": ["transaction"],
        "summary": "gettransactionbyid",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/acceptpayment": {
      "post": {
        "tags": ["payment"],
        "summary": "acceptpayment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "product_items": [
                    {
                      "item_name": "T-shirt",
                      "amount": 2000,
                      "quantity": 1
                    }
                  ],
                  "success_page_url": "http://mangoit-lms.mangoitsol.com/paymentsuccess",
                  "cancel_page_url": "http://mangoit-lms.mangoitsol.com/paymentcancel"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQ2OTE0MywiZXhwIjoxNjkxNDk3OTQzfQ.pc9pLzB5nPOKxmdX_Sf5V_n5xNLRbU31K9nRktki3vw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000/api/getpaymentdetails": {
      "get": {
        "tags": ["payment"],
        "summary": "getpaymentdetails",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNodWJoYW0gQmhhaSIsImVtYWlsIjoic2o4NDY0NzM2QGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTY5MTQ2OTE0MywiZXhwIjoxNjkxNDk3OTQzfQ.pc9pLzB5nPOKxmdX_Sf5V_n5xNLRbU31K9nRktki3vw"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/000": {
      "get": {
        "tags": ["General"],
        "summary": "checkserver",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}
